replicaCount: 3

image:
  repository: sensor-aggregator
  pullPolicy: IfNotPresent
  tag: "1.0"

service:
  type: ClusterIP
  port: 8082

resources: 
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"
